### ISSUE TITLE
Typecho theme from scratch!

### ISSUE THREAD

**Issue by rHanbowChic** [Remelens/Rlngnahth#1]
好厉害！话说为什么要取这个名字？

Re-lon-ease?

Relon-ease?

Relo-nease?

或者是其他的？总感觉这些都不像......

**Comment by Remelens** [comment]
Relon-ease（）

~~本质上是乱打~~

**Comment by rHanbowChic** [comment]
(。・ω・。)
原来是这样。
听起来不太好呢。
R'lng’nahth一类的怎么样qwq

**Comment by Remelens** [comment]
当然）

~~你看我像会起名的人吗（）~~

不过等明天吧）

**Comment by Remelens** [comment]
👌
